server:
  tomcat:
    max-threads: 20
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: biking
  datasource:
    url: jdbc:mysql://localhost:3306/biking
    username: root
    password: pseudo17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
