spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/biking
    username: root
    password: pseudo17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update